version: "3.8"
services:

  #IoT Agent
  iot-agent:
        image: fiware/iotagent-ul
        hostname: iot-agent
        container_name: fiware-iot-agent
        depends_on:
            - mongo-db
        expose:
            - "4061"
            - "7896"
        ports:
            - "4061:4061"
            - "7896:7896"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4061"
            - "IOTA_REGISTRY_TYPE=mongodb"
            - "IOTA_LOG_LEVEL=DEBUG"
            - "IOTA_TIMESTAMP=true"
            - "IOTA_CB_NGSI_VERSION=v2"
            - "IOTA_AUTOCAST=true"
            - "IOTA_MONGO_HOST=mongo-db"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagent-ul"
            - "IOTA_HTTP_PORT=7896"
            - "IOTA_PROVIDER_URL=http://iot-agent:4061"
            - "IOTA_MQTT_HOST=mosquitto"
            - "IOTA_MQTT_PORT=1883"
            - IOTA_DEFAULT_RESOURCE= # Default is blank. I'm using MQTT so I don't need a resource
            - IOTA_DEFAULT_TRANSPORT=MQTT

  # context broker
  orion:
    labels:
      org.fiware: 'tutorial'
    image: fiware/orion:3.5.1
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "1026:1026"  # containerPort:localPort
    command: -dbhost mongo-db -logLevel DEBUG -noCache


  # Database
  mongo-db:
    labels:
      org.fiware: 'tutorial'
    image: mongo:4.2
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - mongo-db:/data


  # Crate-DB Database
  crate-db:
    labels:
      org.fiware: 'tutorial'
    image: crate
    hostname: crate-db
    container_name: db-crate
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    command: ["crate",
              "-Ccluster.name=democluster",
              "-Cnode.name=cratedb01",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Chttp.cors.enabled=true",
              "-Chttp.cors.allow-origin=*",
              "-Cgateway.expected_data_nodes=1"]
              # crate -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    environment:
      - CRATE_HEAP_SIZE=4g # see https://crate.io/docs/crate/howtos/en/latest/deployment/containers/docker.html#troubleshooting
    volumes:
      - crate-db:/data
    healthcheck:
      disable: true

  #Grafana Dashboard
  grafana:
    labels:
      org.fiware: 'tutorial'
      
    image: grafana/grafana:6.1.6
    container_name: grafana
    depends_on:
      - crate-db
    ports:
      - "3003:3000"
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/orchestracities/grafana-map-plugin/archive/master.zip;grafana-map-plugin,grafana-clock-panel,grafana-worldmap-panel
    volumes:
      - grafana:/var/lib/grafana
    
  # Quantum Leap is persisting Short Term History to Crate-DB
  quantumleap:
    labels:
      org.fiware: 'tutorial'
    image: orchestracities/quantumleap
    hostname: quantumleap
    container_name: fiware-quantumleap
    depends_on:
      - crate-db
    networks:
      - default
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate-db
      - LOGLEVEL=DEBUG
    healthcheck:
      test: curl --fail -s http://quantumleap:8668/version || exit 1


  #MQTT
  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.config
    networks:
      - default

networks:
  default:
    labels:
      org.fiware: 'tutorial'
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  mongo-db: ~
  grafana: ~
  crate-db: ~
